sounds={
"ZgBAWQBAQEBAQEBAywlPPh9mAT9T51A+VQBAf0BAQEBAQEBA",
"ZgBAUwBAQEBAQEBAywlPPh9mAT9T51A+VQBAf0BAQEBAQEBA",
"ZgBATABAQEBAQEBAywlPPh9mAT9T51A+VQBAf0BAQEBAQEBA",
"ZgBARgBAQEBAQEBAywlPPh9mAT9T51A+VQBAf0BAQEBAQEBA",
"ZgBAQABAQEBAQEBAywlPPh9mAT9T51A+VQBAf0BAQEBAQEBA",
"ZgBAOQBAQEBAQEBAywlPPh9mAT9T51A+VQBAf0BAQEBAQEBA",
"ZgBAMwBAQEBAQEBAywlPPh9mAT9T51A+VQBAf0BAQEBAQEBA",
"ZgBALABAQEBAQEBAywlPPh9mAT9T51A+VQBAf0BAQEBAQEBA",
"ZgBAJgBAQEBAQEBAywlPPh9mAT9T51A+VQBAf0BAQEBAQEBA",
"ZgBAIABAQEBAQEBAywlPPh9mAT9T51A+VQBAf0BAQEBAQEBA",

"ZgBAIABAQEBAQEBAywlPPh9mAT9T51A+VQBAf0BAQEBAQEBA",
"ZgBAJgBAQEBAQEBAywlPPh9mAT9T51A+VQBAf0BAQEBAQEBA",
"ZgBALABAQEBAQEBAywlPPh9mAT9T51A+VQBAf0BAQEBAQEBA",
"ZgBAMwBAQEBAQEBAywlPPh9mAT9T51A+VQBAf0BAQEBAQEBA",
"ZgBAOQBAQEBAQEBAywlPPh9mAT9T51A+VQBAf0BAQEBAQEBA",
"ZgBAQABAQEBAQEBAywlPPh9mAT9T51A+VQBAf0BAQEBAQEBA",
"ZgBARgBAQEBAQEBAywlPPh9mAT9T51A+VQBAf0BAQEBAQEBA",
"ZgBATABAQEBAQEBAywlPPh9mAT9T51A+VQBAf0BAQEBAQEBA",
"ZgBAUwBAQEBAQEBAywlPPh9mAT9T51A+VQBAf0BAQEBAQEBA",
"ZgBAWQBAQEBAQEBAywlPPh9mAT9T51A+VQBAf0BAQEBAQEBA",
}

local num=1

function gameSound()
    sound(DATA,sounds[num])
    num=num+1
    if num>#sounds then
        num=1
    end
end

function gameSoundReset()
    num=1
end
